'use strict';
/**
 * validate-schema.js
 * ──────────────────
 * Compares every Sequelize model definition against the live PostgreSQL schema.
 * Detects: missing tables, missing columns, NOT NULL mismatches.
 *
 * Usage:
 *   node backend/scripts/validate-schema.js
 *
 * Exit code: 0 = all OK (warnings only), 1 = one or more hard issues found.
 */

// Load .env so DB credentials are available
require('dotenv').config();

const db = require('../models');

// ── PostgreSQL type aliases (what information_schema.data_type returns) ──────
const TYPE_COMPAT = {
  uuid:     ['uuid'],
  string:   ['character varying', 'varchar', 'text', 'character', 'bpchar'],
  text:     ['text', 'character varying'],
  integer:  ['integer', 'int4', 'int', 'smallint', 'bigint'],
  bigint:   ['bigint', 'int8'],
  float:    ['double precision', 'real', 'numeric', 'float8'],
  decimal:  ['numeric', 'decimal'],
  boolean:  ['boolean'],
  dateonly: ['date'],
  date:     ['timestamp with time zone', 'timestamp without time zone', 'timestamp'],
  json:     ['json', 'jsonb'],
  jsonb:    ['jsonb', 'json'],
  // ENUMs are stored as USER-DEFINED in pg information_schema
  enum:     ['user-defined', 'character varying', 'text'],
  virtual:  [],   // Virtual columns have no DB presence – skip
};

// Fields automatically managed by Sequelize – skip these in mismatch checks
const AUTO_FIELDS = new Set(['createdAt', 'updatedAt', 'deletedAt']);

// ── Helpers ──────────────────────────────────────────────────────────────────

async function getDbTables(schema) {
  const [rows] = await db.sequelize.query(
    `SELECT table_name
     FROM information_schema.tables
     WHERE table_schema = :schema AND table_type = 'BASE TABLE'
     ORDER BY table_name`,
    { replacements: { schema } }
  );
  return new Set(rows.map(r => r.table_name));
}

async function getDbColumns(schema, table) {
  const [rows] = await db.sequelize.query(
    `SELECT column_name, data_type, is_nullable, column_default, udt_name
     FROM information_schema.columns
     WHERE table_schema = :schema AND table_name = :table
     ORDER BY ordinal_position`,
    { replacements: { schema, table } }
  );
  const map = {};
  rows.forEach(r => { map[r.column_name] = r; });
  return map;
}

function seqTypeName(field) {
  // DataTypes.UUID → 'uuid', DataTypes.STRING → 'string', etc.
  const t = field.type;
  if (!t) return 'unknown';
  const key = (t.constructor?.key || t.key || t.toString() || '').toLowerCase().split('(')[0].trim();
  return key || 'unknown';
}

function typesCompatible(seqType, dbType) {
  const compat = TYPE_COMPAT[seqType];
  if (!compat) return true; // unknown type – skip check
  if (compat.length === 0) return true; // virtual – skip
  return compat.some(t => dbType.toLowerCase().includes(t));
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function run() {
  const SCHEMA = 'public';
  const issues   = [];
  const warnings = [];
  const passed   = [];

  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║   SkyrakSys HRM — DB Schema Validation Script   ║');
  console.log('╚══════════════════════════════════════════════════╝\n');

  try {
    await db.sequelize.authenticate();
    console.log('✓ Database connected\n');
  } catch (err) {
    console.error('✗ Cannot connect to database:', err.message);
    process.exit(1);
  }

  const dbTables = await getDbTables(SCHEMA);

  for (const [modelName, Model] of Object.entries(db)) {
    if (modelName === 'sequelize' || modelName === 'Sequelize') continue;
    if (!Model?.rawAttributes) continue;

    const rawTableName = Model.getTableName?.();
    const tableName = typeof rawTableName === 'string'
      ? rawTableName
      : rawTableName?.tableName ?? String(rawTableName);

    // ── Table existence ──────────────────────────────────────────────────────
    if (!dbTables.has(tableName)) {
      issues.push(`[MISSING TABLE] Model "${modelName}" expects table "${tableName}" — not found in DB`);
      continue;
    }

    const dbColMap = await getDbColumns(SCHEMA, tableName);
    let modelIssues = 0;
    let modelOk = 0;

    for (const [fieldName, field] of Object.entries(Model.rawAttributes)) {
      // Skip timestamps managed by Sequelize
      if (AUTO_FIELDS.has(fieldName) && field._autoGenerated) continue;

      // Skip virtual fields (no DB column)
      const seqType = seqTypeName(field);
      if (seqType === 'virtual') continue;

      const colName = field.field || fieldName; // handles camelCase → snake_case mapping
      const dbCol = dbColMap[colName];

      // ── Column existence ───────────────────────────────────────────────────
      if (!dbCol) {
        const severity = field.allowNull === false ? 'issues' : 'warnings';
        const label = field.allowNull === false ? '[MISSING COLUMN ⚠]' : '[MISSING COLUMN]';
        const bucket = field.allowNull === false ? issues : warnings;
        bucket.push(
          `${label} ${modelName}.${fieldName} → column "${colName}" not in table "${tableName}"`
          + (field.allowNull === false ? ' (NOT NULL — will crash on insert)' : '')
        );
        modelIssues++;
        continue;
      }

      // ── NOT NULL alignment ─────────────────────────────────────────────────
      const modelNN = field.allowNull === false;
      const dbNN    = dbCol.is_nullable === 'NO';

      if (modelNN && !dbNN) {
        issues.push(
          `[NOT NULL MISMATCH] ${modelName}.${fieldName} — Model: allowNull=false, DB: nullable (table "${tableName}", col "${colName}")`
          + ' — Sequelize will not enforce constraint; unexpected NULLs can enter DB'
        );
        modelIssues++;
      } else if (!modelNN && dbNN && !field.defaultValue && colName !== 'id') {
        warnings.push(
          `[NOT NULL MISMATCH] ${modelName}.${fieldName} — Model: allowNull=true, DB: NOT NULL (table "${tableName}", col "${colName}")`
          + ' — DB will reject insert if this field is omitted'
        );
        modelIssues++;
      }

      // ── Type compatibility ─────────────────────────────────────────────────
      if (seqType !== 'unknown' && seqType !== 'virtual') {
        const dbType = dbCol.data_type.toLowerCase();
        if (!typesCompatible(seqType, dbType)) {
          warnings.push(
            `[TYPE MISMATCH] ${modelName}.${fieldName} — Model: ${seqType}, DB: ${dbType} (col "${colName}")`
          );
          modelIssues++;
          continue;
        }
      }

      modelOk++;
    }

    if (modelIssues === 0) {
      passed.push(`  ✓  ${modelName.padEnd(22)} table: ${tableName.padEnd(28)} (${modelOk} fields)`);
    }
  }

  // ── Output ────────────────────────────────────────────────────────────────
  if (passed.length) {
    console.log('PASSED MODELS:');
    passed.forEach(l => console.log(l));
  }

  if (warnings.length) {
    console.log(`\nWARNINGS (${warnings.length}) — review manually:`);
    warnings.forEach(w => console.log('  ⚠  ' + w));
  }

  if (issues.length) {
    console.log(`\nISSUES (${issues.length}) — likely bugs:`);
    issues.forEach(i => console.log('  ✗  ' + i));
  }

  console.log(
    `\n${'─'.repeat(54)}\n` +
    `  ${passed.length} models OK   ` +
    `${warnings.length} warnings   ` +
    `${issues.length} issues\n` +
    `${'─'.repeat(54)}\n`
  );

  process.exit(issues.length > 0 ? 1 : 0);
}

run().catch(err => {
  console.error('\nFatal error:', err.message);
  process.exit(1);
});
